#!/usr/bin/env bash
# While loop that displays "Best School" 10 times and "Hi" on the 9th line.
count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi 
	echo "Best School"
	(( count++ ))
done
