#!/usr/bin/env bash
# While loop with 10 iterations that displays "Best School" "bad luck 4th loop" "good luck 8th loop" 

i=1
while [ $i -lt 11 ]
do
if [ $i = 4 ]
then
echo "bad luck"
elif [ $i = 8 ]
then
echo "good luck"
else
echo "Best School"
fi
(( i++ ))
done
